version: "3.8"

services:
  api:
    build: .
    container_name: peopleflow-api
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - .:/app
    command: python app/main.py

  mongo:
    image: mongo:6
    container_name: peopleflow-mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: peopleflow

volumes:
  mongo_data:
